
name: repo-sync
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
  
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: sync lxk0301-scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://gitee.com/lxk0301/jd_scripts.git"
          source_branch: "master"
          destination_branch: "master"
          github_token: ${{ secrets.PAT }}        
  fix-env:
    needs: repo-sync
    env:
      PAT: ${{ secrets.PAT }}      
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: 'Apply fix-env changes'
      run: |
             sed -i 's/'GITHUB'/'BUHTIG'/g' *.js
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply fix-env changes
        branch: master
